version: '3'

services:
  app:
    build:
      context: ./app
    container_name: node_app
    ports:
      - "3000:3000"
    networks:
      - node-network

  db:
    image: mysql:8.3.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/data:/var/lib/mysql:z
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MYSQL_DATABASE=nodeapp
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    image: felipepassada/nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge
